### ISSUE TITLE
Failed to load video: The operation could not be completed

### ISSUE THREAD

**Issue by chenliang0571** [ollydixon/flutter_macos_video_player#10]
```
Unhandled Exception: PlatformException(VideoError, Failed to load video: The operation could not be completed, null, null)
```
for both network and file: 
* `VideoPlayerController.network('https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4'...`
* `VideoPlayerController.file(File('/tmp/Butterfly-209.mp4'))`

```
dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.4.5
  video_player_macos: 1.0.6
```

sample: https://github.com/chenliang0571/video_player/tree/master/video_player/example
